# Generated by Django 5.2.1 on 2025-06-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollnumber', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
